# Generated by Django 4.1.7 on 2023-05-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_employee_rename_code_dept_code_rename_id_dept_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
